### PR TITLE
Redact credentials in events page

### LINKED ISSUE #2911: Stolen credentials can be seen plaintext
## Describe the bug
Stolen credentials event is encrypted in the database, but on the UI, those credentials are shown plaintext in "Events" page

## To Reproduce
1. Configure the Monkey to steal credentials
2. Go to "Events" page and open up "CredentialsStolenEvent"
3. See stolen credentials plaintext

## Expected behavior
Should not show stolen credentials in plaintext. Credential type is enough. 

## Screenshots
image

## Machine version (please complete the following information):
 - OS: Windows or Linux

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #2911

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js [hunk 1]
```diff
@@ -87,7 +89,26 @@ function deleteAbstractAgentEventFields(myObj) {
...
+  let tempObj = JSON.parse(JSON.stringify(myObj)); /* deepcopy */
+
+  let stolenCredentialsFieldName = "stolen_credentials";
+  let secretFieldName = "secret";
+
+  if (tempObj.hasOwnProperty(stolenCredentialsFieldName)) {
+    for (let stolenCredential of tempObj[stolenCredentialsFieldName]) {
+      let secrets = stolenCredential[secretFieldName];
+      for (let secretType in secrets) {
+        let redactedSecret = "*".repeat(stolenCredential[secretFieldName][secretType].length);
```
Comment (ilija-lazoroski) [inline monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js:102]: Can we have some fixed length as this gives away the actual length of the credential?

Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js:102]: I don't think it really matters.

File: monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js [hunk 2]
```diff
@@ -87,7 +89,26 @@ function deleteAbstractAgentEventFields(myObj) {
   return tempObj;
 }
 
-const renderEventSpecificFields = (val) => filterEventSpecificFields(val);
+function redactSecretsInEventFields(myObj) {
+  let tempObj = JSON.parse(JSON.stringify(myObj)); /* deepcopy */
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/ui-components/EventsTable.js:93]: Stay consistent, use `_.copydeep`. More elegant and expressive
