### PR TITLE
Fix StolenCredentialsTable bug

### LINKED ISSUE #2923: Stolen Credentials table clears out when switching to between reports
## Describe the bug
When switching between the Security and Ransomware reports, the Stolen Credentials table of the Security report is cleared out. Switching to a different page (e.g. Configuration) and then back to the Report will cause the report to reload and the Stolen Credentials to be repopulated.

## To Reproduce
1. Use a configuration that steals credentials, such as the one from the credentials_reuse_ssh_key test, or the zerologon test.
2. Run the monkey
3. Observe that the stolen credentials are in the table in the Security report
4. Switch to the Ransomware report
5. Switch back to the Security report
6. Observe that the Stolen Credentials table is now empty

## Expected behavior
The Stolen Credentials table should remain populated.

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #2923 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island
* [x] If applicable, add screenshots or log transcripts of the feature working

image

https://user-images.githubusercontent.com/44770317/216921902-2af33d1e-8d3b-44ee-9eec-43c62c10322b.mp4

### CODE REVIEW

**Review by VakarisZ — APPROVED** [review]

File: monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx [hunk 1]
```diff
@@ -17,31 +18,32 @@ const columns = [
...
+    IslandHttpClient.get(APIEndpoint.stolenCredentials).then(
+      res => setCredentialsTableData(getCredentialsTableData(res.body))
     );
+  }, [])
+
+  if (credentialsTableData === null) {
+    return <LoadingIcon />
   }
+
+  let defaultPageSize = credentialsTableData.length > pageSize ? pageSize : credentialsTableData.length;
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx:35]: Shouldn't we get "line too long" error?

**Review by ilija-lazoroski — APPROVED** [review]

File: monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx (hunk 1 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx:35]: Apparently not, Travis passed
