### PR TITLE
Use machine ID for machine recommendations in security report

### LINKED ISSUE #2588: "Machine related recommendations" bug in security report if hostname is same for two machines
## Describe the bug
The "change user password" issue is shown twice in the security report for the powershell-45 (10.2.3.45) machine in the zoo, and no issue is shown for the powershell-45 (10.2.2.47) machine.

## To Reproduce
1. Run the Agent to exploit 10.2.3.45 and 10.2.3.47 (see depth_3_a configuration).
2. Check security report.

## Expected behavior
The issue for the 10.2.3.47 machine should be shown separately. This is probably happening because the hostnames of the machines are the same. The logic should be modified to check both hostname and IP.

## Screenshots
image

## Tasks
- [ ] Fix it - (0.25d)

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #2588 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?`
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by on GCP, see screenshot
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx [hunk 1]
```diff
@@ -61,6 +61,16 @@ export function getMachineHostname(machine): string {
   return hostname;
 }
 
+export function getMachineFromID(id, machines) {
+  for (let machine of machines) {
+    if (machine.id === id) {
+      return machine;
+    }
+  }
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx:69]: Doing 
```
return machines.filter((machine) => machine.id === id)[0] || null
```
Would be more concise

File: monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx [hunk 2]
```diff
@@ -61,6 +61,16 @@ export function getMachineHostname(machine): string {
   return hostname;
 }
 
+export function getMachineFromID(id, machines) {
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx:64]: should be `getMachineByID`, because we're not creating a machine FROM id, we're fetching it from the list BY it's id. Same goes for `getMachineFromIP`

File: monkey/monkey_island/cc/services/reporting/report.py [hunk 3]
```diff
@@ -225,6 +226,7 @@ def get_island_cross_segment_issues(cls):
             if not found_good_ip:
                 issues.append(
                     {
+                        "id": island_machine.id,
                         "type": "island_cross_segment",
                         "machine": island_machine.hostname,
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/services/reporting/report.py:231]: We probably no longer need this, because if we have `machine_id` then we can pull its hostname anytime. But I imagine this would cause a bigger refactoring

File: monkey/monkey_island/cc/services/reporting/report.py [hunk 4]
```diff
@@ -225,6 +226,7 @@ def get_island_cross_segment_issues(cls):
             if not found_good_ip:
                 issues.append(
                     {
+                        "id": island_machine.id,
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/services/reporting/report.py:229]: This is not an "id" of the issue, this is `machine_id`

File: monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js [hunk 5]
```diff
@@ -18,17 +18,27 @@ export function getAllTunnels(agents, machines) {
...
+        let agentMachineInfo = {
+          'id': agentMachine.id,
+          'ip': getMachineIPs(agentMachine)[0],
+          'hostname': getMachineHostname(agentMachine)
+        };
+
+        let agentTunnelMachineInfo = {
+          'id': -1,
+          'ip': agent.cc_server.ip,
+          'hostname': agent.cc_server.ip
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js:30]: use `null` here. We're parsing data, not determining what to display here

File: monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js [hunk 6]
```diff
@@ -18,17 +18,27 @@ export function getAllTunnels(agents, machines) {
...
+        };
 
-        let agentTunnelMachineHostname = agent.cc_server.ip;
         let agentTunnelMachine = getMachineFromIP(agent.cc_server.ip, machines)
         if (agentTunnelMachine !== null) {
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js:34]: We'll run into issues if this happens. For example the `id` could be the same for multiple machines, so multiple components will have the same key, which will result in an error.

File: monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js [hunk 7]
```diff
@@ -18,17 +18,27 @@ export function getAllTunnels(agents, machines) {
...
-          agentTunnelMachineHostname = getMachineHostname(agentTunnelMachine);
+          agentTunnelMachineInfo.id = agentTunnelMachine.id;
+          agentTunnelMachineInfo.hostname = getMachineHostname(agentTunnelMachine);
         }
 
         tunnels.push({
-          'agent_machine': agentMachineHostname,
-          'agent_tunnel': agentTunnelMachineHostname
+          'agent_machine': agentMachineInfo,
+          'agent_tunnel': agentTunnelMachineInfo
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js:41]: I'd use `tunnel_machine` instead, here and in the variables. The word `agent` adds no context in this case. `agent_machine` makes sense because it's the MACHINE where AGENT ran.

File: monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js [hunk 8]
```diff
@@ -515,13 +516,15 @@ class ReportPageComponent extends AuthComponent {
...
     let issuesDivArray = [];
-    for (let machine of Object.keys(issues)) {
+    for (let machineId of Object.keys(issues)) {
+      let machine = getMachineFromID(parseInt(machineId), this.state.machines);
+      let hostname = getMachineHostname(machine);
       issuesDivArray.push(
-        <li key={JSON.stringify(machine)}>
-          <h4><b>{machine}</b></h4>
+        <li key={machineId}>
+          <h4><b>{hostname}</b></h4>
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js:524]: This is missleading as it might be IP.

File: monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx (hunk 1 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/utils/ServerUtils.tsx:69]: I'd prefer to leave it as is for readibility.

File: monkey/monkey_island/cc/services/reporting/report.py (hunk 3 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/services/reporting/report.py:231]: It would and considering that we're going to rework this anyway, I'd rather not touch it.

File: monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js (hunk 6 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/report-components/security/issues/TunnelIssue.js:34]: When would the machine ID be the same for multiple machines?

File: monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js (hunk 8 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js:524]: I agree. It should be something like `display_name`. However, this hostname/IP thing is in a bunch of places in the codebase, so again, I'd say we put it off until to when we refactor the report.
