### PR TITLE
Fix UI bug in ATT&CK Report

### LINKED ISSUE #948: UI bug in attack report
## Describe the bug
Attack report crashes upon second visit.
image

## To Reproduce
1. Run monkey
2. Go to report to assess results
3. Switch between attack report and another tab a couple of times. I get this bug:
image

## Expected behavior
Shouldn't crash.

## Machine version (please complete the following information):
 - OS: Windows

### PR DESCRIPTION
**Pull request by shreyamalviya**
Fixes #948

https://user-images.githubusercontent.com/44770317/106280536-11cf9300-6264-11eb-8e6f-c70d66e4292b.mp4

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js [hunk 1]
```diff
@@ -159,7 +159,9 @@ class AttackReport extends React.Component {
     }
     // modify techniques' messages
     for (const tech_id in techniques){
-      techniques[tech_id]['message'] = <div dangerouslySetInnerHTML={{__html: marked(techniques[tech_id]['message'])}} />;
+      if (typeof techniques[tech_id]['message'] === 'string') {
```
Comment (mssalvatore) [inline monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js:162]: Do we understand why the messages are objects instead of strings. What is the root cause of this issue? Are we just side-stepping it by checking the type?

Comment (VakarisZ) [reply monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js:162]: `marked()` modifies them in place. We need to change this behaviour(maybe there's a param for this? maybe we pass a copy of the string instead?)

Comment (mssalvatore) [reply monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js]: @VakarisZ Does `marked()` modify in place? All of the usage I can find implies that it returns a value, and javascript strings are immutable. **https://marked.js.org/**

File: monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js [hunk 2]
```diff
@@ -157,11 +157,9 @@ class AttackReport extends React.Component {
         }
       }
     }
-    // modify techniques' messages
+    // compiles techniques' message string from markdown to HTML
     for (const tech_id in techniques){
-      if (typeof techniques[tech_id]['message'] === 'string') {
-        techniques[tech_id]['message'] = <div dangerouslySetInnerHTML={{__html: marked(techniques[tech_id]['message'])}} />;
-      }
+      techniques[tech_id]['message'] = <div dangerouslySetInnerHTML={{__html: marked(techniques[tech_id]['message_string'])}} />;
```
Comment (mssalvatore) [inline monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js:162]: Rather than change `message` -> `message_string`, what about storing the result of this line in `techniques[tech_id]['message_html']`? It would require other code changes, but the intent might be clearer.

We should also drop any unnecessary commits from the PR (force push) so we don't muddy up the commit history.

**Review by mssalvatore — CHANGES_REQUESTED** [review]

File: monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js (hunk 1 above)
Comment (mssalvatore) [reply monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js]: Oh, I think you mistyped and meant that `modifyTechniqueData()` modifies in-place. I think we're on the same page.

File: monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js (hunk 2 above)
Comment (shreyamalviya) [reply monkey/monkey_island/cc/ui/src/components/report-components/AttackReport.js]: Done

**Review by mssalvatore — APPROVED** [review]
