### PR TITLE
Show only configured IPs for Run Monkey -> Manual page

### LINKED ISSUE #953: Run Monkey -> Manual - Ignores Island IPs from config
## Describe the bug
The "Run Monkey" page does not appear to consult the configuration when setting IP address options.

## To Reproduce
1. Run Monkey Island on a system with multiple IPs
2. In _Configuration_ > _Internal_ > _Island Server_, remove one or more IPs from "Island Server IPs"
3. Submit config
4. Go to _Run Monkey_ > _Manual_ and see that the IPs that were removed from the configuration are still options

## Expected behavior
If an IP is not a configured Island Server IP, it should not appear in the Run Monkey options.

## Screenshots
island_server_ips

## Machine version (please complete the following information):
 - OS: Linux

### PR DESCRIPTION
**Pull request by shreyamalviya**
Fixes #953

Only configured Island Server's IPs appear on the Run Monkey -> Manual page.

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js [hunk 1]
```diff
@@ -20,12 +22,16 @@ function RunOptions(props) {
...
     if (initialized === false) {
-      authComponent.authFetch('/api')
-        .then(res => res.json())
-        .then(res => {
-          setIps([res['ip_addresses']][0]);
-          setInitialized(true);
+      authComponent.authFetch(CONFIG_URL)
+      .then(res => res.json())
+      .then(res => {
+        let commandServers = res.configuration.internal.island_server.command_servers;
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js:28]: We really need to test this somehow. If we change configuration structure or rename a single field, this will silently break. Next quarter we should look into UI unit tests, but for now I suggest you add a unit test in the back end, which verifies that this path indeed exists.

File: monkey/monkey_island/cc/services/tests/test_config.py [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+                        lambda: IPS)
+    monkeypatch.setattr(Environment, "_ISLAND_PORT", PORT)
+    config = ConfigService.get_default_config(True)
+    return config
+
+
+def test_set_server_ips_in_config_command_servers(config):
+    ConfigService.set_server_ips_in_config(config)
+    expected_config_command_servers = [f"{ip}:{PORT}" for ip in IPS]
+    assert config["internal"]["island_server"]["command_servers"] ==\
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/services/tests/test_config.py:23]: It's good that you added a unit test, but we also need to add a comment that would link this to UI: "If config path changed, we need to synch it with  monkey/monkey_island/cc/ui/src/components/pages/RunMonkeyPage/RunOptions.js"

**Review by VakarisZ — APPROVED** [review]
Good work
