### PR TITLE
Replaced starting tilda with home directory. Related #1108.

### LINKED ISSUE #1108: Bug with deployment script linux
#Tasks:

- [ ]  Fix the bug (0.25)

## Describe the bug
Documentation of deployment script for Linux describes usage as `./deploy_linux.sh "/home/user/new" "master"`.
When I tried command `./deploy_linux.sh "~/infection_monkey_deployment_test" "pipenv"`, a new directory "~" was created in a working directory, inside it infection_monkey_deployment_test dir was created. Either documentation is bad or there's a bug with directory creation

## Machine version (please complete the following information):
 - OS: Linux

### PR DESCRIPTION
**Pull request by ilija-lazoroski**
# What does this PR do? 

Fixes #1108 .

Add any further explanations here. 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by {Running the Monkey locally with relevant config/running Island/...} 
* [x] If applicable, add screenshots or log transcripts of the feature working

## Explain Changes

Are the commit messages enough? If not, elaborate.

### CODE REVIEW

File: deployment_scripts/deploy_linux.sh [hunk 1]
```diff
@@ -63,6 +63,10 @@ log_message "loaded configuration"
 
 # Setup monkey either in dir required or current dir
 monkey_home=${1:-$(pwd)}
+
+# Replace front ~ with the home directory
+monkey_home=${monkey_home/#'~'/$HOME}
```
Comment (mssalvatore) [inline deployment_scripts/deploy_linux.sh:68]: This is an incomplete solution. A path like "~/my-stuff" will evaluate to "$HOME/my-stuff", but a path like "~user/my-stuff" should evaluate to "/home/user/my-stuff". Using string substitution results in "$HOMEuser/my-stuff".

Good work in tracking down the source of the issue, though. IMHO, this is actually a non-issue. If the tilde is quoted, then the script behaves as expected. I'll leave some comments on the original issue.

**Review by mssalvatore — APPROVED** [review]
