### PR TITLE
Bugfix/handle missing curl wget fixes #503

### LINKED ISSUE #503: Installation from .deb fails  on Ubuntu machine which doesn't have curl installed
## Describe the bug
When trying to install `monkey_island.deb` on an Ubuntu machine without `curl` installed, mongo won't run but the installation fails silently. 

## To Reproduce
1. Set up an Ubuntu machine without curl installed
2. Try to install Monkey Island from deb
3. Run `sudo systemctl status monkey-island`
4. See that the server is waiting for mongo

## Expected behavior
Should install all required dependencies.

## Machine version (please complete the following information):
 - OS: Ubuntu without curl
 - Version: 1.7

### PR DESCRIPTION
**Pull request by danielguardicore**
# What is this? 
Fixes #503 by adding option to use wget or curl as long as one is installed.
Also took the time to cleanup the script.

## Checklist
* [X] Have you added an explanation of what your changes do and why you'd like to include them?
* [X] Have you successfully tested your changes locally?
* [ ] Is the TravisCI build passing? 

## Proof that it works
None yet

### CODE REVIEW

File: deployment_scripts/deploy_linux.sh [hunk 1]
```diff
@@ -1,10 +1,14 @@
 #!/bin/bash
 source config
 
+exists() {
+  command -v "$1" >/dev/null 2>&1
+}
+
```
Comment (ShayNehmad) [inline deployment_scripts/deploy_linux.sh]: Unused here?

File: monkey/monkey_island/linux/install_mongo.sh [hunk 2]
```diff
@@ -1,40 +1,58 @@
...
+  exit 1
+}
+
+if exists bash; then
+  wget ${tgz_url} -O mongodb.tgz
+else
+  if exists curl; then
+    curl --output mongodb.tgz ${tgz_url}
+  else
+    echo 'Your system has neither curl nor wget, exiting'
```
Comment (ShayNehmad) [inline monkey/monkey_island/linux/install_mongo.sh]: We're not checking `wget` so this error message is incorrect. We should also add "To fix this, please run\n apt install curl\n and re-run this script"

File: deployment_scripts/deploy_linux.sh (hunk 1 above)
Comment (danielguardicore) [reply deployment_scripts/deploy_linux.sh]: Yeah, it's prep for later code. I can remove from this PR but it'll just sneak back in later on

File: monkey/monkey_island/linux/install_mongo.sh (hunk 2 above)
Comment (danielguardicore) [reply monkey/monkey_island/linux/install_mongo.sh]: Woops, typo. WIll be fixed.

File: deployment_scripts/deploy_linux.sh (hunk 1 above)
Comment (ShayNehmad) [reply deployment_scripts/deploy_linux.sh]: Then leave it, but I'm giving myself a gold star for effort 🌟

**Comment by danielguardicore** [comment]
> ℃⁜※⁋¶

Wat

File: monkey/monkey_island/linux/install_mongo.sh [hunk 3]
```diff
@@ -1,40 +1,58 @@
...
 
 TEMP_MONGO=$(mktemp -d)
-pushd ${TEMP_MONGO}
-wget ${tgz_url} -O mongodb.tgz
+pushd "${TEMP_MONGO}" || {
+  echo "Pushd failed"
+  exit 1
+}
+
+if exists wget; then
```
Comment (VakarisZ) [inline monkey/monkey_island/linux/install_mongo.sh]: Notice that mongodb is installed after some wget calls in the deployment scripts, so it would be best to also add the same check to the `deploy_linux.sh`

Comment (danielguardicore) [reply monkey/monkey_island/linux/install_mongo.sh]: Added

**Comment by danielguardicore** [comment]
@VakarisZ take a look and test please. If ok, I want to merge this then work on removing need for further downloads
