### PR TITLE
Package appimage with linuxdeploy

### LINKED ISSUE #1355: MongoDB is not starting on CentOS 7
## Describe the bug
While running the AppImage on CentOS 7, the Island log showed that MongoDB has started successfully and then stuck on waitng for MongoDB server. The mongodb log shows that `libcrypto.so.1.1` is missing.

## To Reproduce
1. Run AppImage
2. Check the Island log
3. See error in `.monkey_island/mongodb.log` 

## Expected behavior
The MongoDB should have started without errors.

## Screenshots
image

image

## Machine version (please complete the following information):
 - OS:  Linux

### LINKED ISSUE #1362: Add libcurl to Appimage
Some Ubuntu systems may not have libcurl installed by default. Add it to the AppImage so that the AppImage package does not require the user to perform any extra steps to install it.

### PR DESCRIPTION
**Pull request by mssalvatore**
# What does this PR do? 

Fixes #1355
Fixes #1362

Add any further explanations here. 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 

## Testing Checklist

* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by  running on Ubuntu Bionic, Ubuntu Focal, and Rocky 8

### CODE REVIEW

File: build_scripts/appimage/appimage.sh [hunk 1]
```diff
@@ -61,75 +62,61 @@ setup_python_37_appdir() {
...
-  cp ./infection-monkey.desktop "$appdir"/usr/share/applications
-  ln -s "$appdir"/usr/share/applications/infection-monkey.desktop "$appdir"/infection-monkey.desktop
-}
-
-add_apprun() {
-  cp ./AppRun "$1"
+remove_python_appdir_artifacts() {
+  unlink "$APPDIR"/python.png
+  unlink "$APPDIR"/python*.desktop
+  unlink "$APPDIR"/AppRun
```
Comment (VakarisZ) [inline build_scripts/appimage/appimage.sh:101]: Why unlink instead or `rm`?

**Review by VakarisZ — APPROVED** [review]

File: build_scripts/appimage/appimage.sh (hunk 1 above)
Comment (mssalvatore) [reply build_scripts/appimage/appimage.sh:101]: Probably because some of them were symlinks, and I use `unlink` for symlinks instead of `rm`; not because it does anything substantively different, just because that's how my brain works. I cam make them `rm` instead.
