### PR TITLE
2595 add missing log filenames in error modal

### LINKED ISSUE #2595: Download useful log file if a machine is exploited twice
## Describe the bug
A machine being exploited multiple times means that multiple Agents will try to run on that machine. Our logic makes sure that an Agent doesn't run if there's another one running already, however, that doesn't extend to the logs. If I try to download the Agent log of such a machine, it downloads the latest (haven't verified that it's actually the *latest*) Agent's logs.

## To Reproduce
1. Configure the Monkey so that a machine gets exploited twice (depth_3_a test should work).
2. Try to download the log from a machine that has been exploited multiple times (mimikatz-15 in depth_3_a).
 
## Expected behavior
The log file of the Agent that ran first should be downloaded. Or all of them should be downloaded.

## Logs
Log file that I got from mimikatz-15 when running depth_3_a:
[2022-11-16T14.28.33.664Z-mimikatz-15.log](https://github.com/guardicore/monkey/files/10022825/2022-11-16T14.28.33.664Z-mimikatz-15.log)

## Tasks
- [x] Modify the log download component to download all agent logs on a machine if multiple agents ran on that machine (0d) @ilija-lazoroski 
- [ ] Fix ErrorModal in `LogDownloadButtons` to include missing agent logs. (0.25d)

### PR DESCRIPTION
**Pull request by ilija-lazoroski**
# What does this PR do?

Fixes #2595.

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running bunch of times, deleting and checking error modal
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/ui-components/ErrorModal.tsx [hunk 1]
```diff
@@ -36,7 +36,7 @@ export const ErrorModal = ({
           <div>
             <hr/>
             <h4>Error Details</h4>
-            <p style={{'word-wrap': 'break-word'}}>
+            <p style={{'word-wrap': 'break-word', 'white-space': 'pre-wrap'}}>
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/ui-components/ErrorModal.tsx:39]: Avoid in-line styling in the future

**Review by mssalvatore — APPROVED** [review]
