### PR TITLE
Fix empty log file download bug

### LINKED ISSUE #2586: Empty log file downloaded if file does not exist anymore
## Describe the bug
If an Agent's log file is deleted, the download log button on the Map page's preview pane doesn't update (it should be gray if a log file doesn't exist), and when clicked, downloads an empty file of the same name.

## To Reproduce
1. Run the Island and an Agent. Go the Map page and click on the machine on which the Agent was run. See that the download Agent log button is yellow and click on it to verify that the file gets downloaded.
2. Delete that Agent's log file.
3. Go to the Map page. The button is still yellow and clicking on it download's an empty file with the same name.

## Expected behavior
The island should return a 404 error if a log doesn't exist. The user should get some kind of notification.

## Tasks
- [x] Ensure that the Island returns a 404 if the log doesn't exist (0d) - @shreyamalviya 
- [ ] Notify the user that the requested log file doesn't exist. (0.25d) - @shreyamalviya 
    - [ ] Preferably, always handle 404 errors in the UI the same way

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #2586 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the Island
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

**Review by mssalvatore — CHANGES_REQUESTED** [review]
My concern here is that there's nothing that will make that text go away. The UI won't know if the file magically reappears and becomes downloadable. In other words, I think this error needs to be somehow "dismissible" by the user.

I'm thinking we should do something more like this: 
image

You can use a [Bootstrap Alert](https://getbootstrap.com/docs/4.2/components/alerts/) to do it.

I think @VakarisZ had some other ideas about how to display the error in a dismissible way.

**Comment by shreyamalviya** [comment]
image

File: monkey/monkey_island/cc/ui/src/components/ui-components/Error404Modal.js [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    return (
+      <Modal show={this.state.showModal} onHide={() => this.props.onClose()}>
+        <Modal.Header closeButton>
+          <Modal.Title> Uh oh... </Modal.Title>
+        </Modal.Header>
+        <Modal.Body>
+          <div style={{'marginTop': '1em', 'marginBottom': '1em'}}>
+            <p className="alert alert-danger">
+              <FontAwesomeIcon icon={faExclamationTriangle} style={{'marginRight': '5px'}}/>
+              The server returned a 404 (NOT FOUND) response.
```
Comment (ilija-lazoroski) [inline monkey/monkey_island/cc/ui/src/components/ui-components/Error404Modal.js:35]: Can we add a custom message to this component and just rename it ErrorModal? We can probably reuse it in other place too.

**Review by ilija-lazoroski — APPROVED** [review]

**Review by mssalvatore — APPROVED** [review]
