### PR TITLE
UI: Fix error handling in configuration import

### LINKED ISSUE #2920: White screen on invalid config import
## Describe the bug
UI crashes on config import if the configuration is not valid

## To Reproduce
1. Try to import invalid configuration
2. Get white screen

Edit:
I'm not sure how I got this behavior, but it seems like the repository cached empty plugins and that's what it's returning. I'll investigate tomorrow, this might be some kind of local issue

## Expected behavior

Error message should appear

### PR DESCRIPTION
**Pull request by VakarisZ**
# What does this PR do?

Fixes #2920

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [ ] Is the TravisCI build passing?
* [ ] Was the CHANGELOG.md updated to reflect the changes?
* [ ] Was the documentation framework updated to reflect the changes?
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] Added relevant unit tests?
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by manually trying different malformed/outdated configs
* [ ] If applicable, add screenshots or log transcripts of the feature working

### CODE REVIEW

**Review by ilija-lazoroski — APPROVED** [review]

File: monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx [hunk 1]
```diff
@@ -196,16 +221,18 @@ const ConfigImportModal = (props: Props) => {
         <div className={`mb-3 config-import-option`}>
           {showVerificationDialog()}
           <Form>
-            <Form.File id='importConfigFileSelector'
-                       label='Please choose a configuration file'
-                       accept='.conf'
+            <Form.File id="importConfigFileSelector"
+                       label="Please choose a configuration file"
+                       accept=".conf"
```
Comment (shreyamalviya) [inline monkey/monkey_island/cc/ui/src/components/configuration-components/ImportConfigModal.tsx:226]: Why double quotes here?

**Review by shreyamalviya — APPROVED** [review]
