### PR TITLE
2288 UI duplicate credentials

### LINKED ISSUE #2288: Inconsistency in the way empty lists are shown in the Security report
## Describe the bug
Empty lists are shown inconsistently in the UI.

## To Reproduce
1. Run the Island
2. Configure it to have 0 usernames and 0 credentials for brute-forcing
3. Run the Agent (just to generate the report)
4. Check Security report

## Expected behavior
Empty lists should be shown in the UI in a consistent way.

## Screenshots
image

## Tasks
- [x] Fix list display (0d) - @shreyamalviya 
- [ ] Fix duplicate credentials (0.5d) - @VakarisZ

### PR DESCRIPTION
**Pull request by VakarisZ**
# What does this PR do?

Fixes #2288

Add any further explanations here.

## PR Checklist
* [ ] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~~Was the CHANGELOG.md updated to reflect the changes?~~
* [ ] ~~Was the documentation framework updated to reflect the changes?~~
* [ ] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~~Added relevant unit tests?~~
* [ ] Have you successfully tested your changes locally? Elaborate:
    > Tested by verifying no duplication appears in report components
* [ ] If applicable, add screenshots or log transcripts of the feature working

### CODE REVIEW

**Comment by VakarisZ** [comment]
Please test the case where no credentials were used or stolen. I get an error in that case

File: monkey/monkey_island/cc/ui/src/components/report-components/security/AvailableCredentials.tsx [hunk 1]
```diff
@@ -0,0 +1,31 @@
+import {getAllUsernames, getAllSecrets} from '../credentialParsing';
+import React from 'react';
+
+const AvailableCredentials = (props) => {
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/AvailableCredentials.tsx:4]: These are available, not used. This will show up even if no brute-force exploiters were enabled

File: monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+];
+
+const pageSize = 10;
+
+const StolenCredentialsTable = () => {
+
+  const [credentialsTableData, setCredentialsTableData] = useState(null);
+
+  useEffect(() => {
+    IslandHttpClient.get(APIEndpoint.stolenCredentials)
```
Comment (cakekoa) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx:26]: `SecurityReport` is already pulling this data. Would it be better to pass that info to this component, rather than fetch the data twice?

File: monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.tsx [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+  content: string
+}
+
+export function getAllSecrets(stolen, configured=[]) {
+  let secrets = [];
+  let stolenSecrets = stolen.map(cred => cred['secret']).filter(cred => cred !== null);
+  let configuredSecrets = configured.map(cred => cred['secret']).filter(cred => cred !== null);
+  let allSecrets = [...stolenSecrets, ...configuredSecrets];
+
+  for (let i = 0; i < allSecrets.length; i++) {
```
Comment (mssalvatore) [inline monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.tsx:32]: Can we:
```suggestion
  for (let i in allSecrets) {
```

File: monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.tsx [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+
+export function getAllUsernames(stolen, configured): string[]{
+  let usernames = new Set([...(getCredentialsUsernames(stolen)),
+    ...getCredentialsUsernames(configured)])
+  return Array.from(usernames);
+}
+
+export function getCredentialsUsernames(credentials): string[]{
+  let usernames = [];
+  for (let i = 0; i < credentials.length; i++) {
```
Comment (mssalvatore) [inline monkey/monkey_island/cc/ui/src/components/report-components/credentialParsing.tsx:12]: Can we use `for...in`?

File: monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+  }
+}
+
+export default StolenCredentialsTable;
+
+
+function getCredentialsTableData(credentials){
+  let tableData = [];
+
+  for (let i = 0; i < credentials.length; i++) {
```
Comment (mssalvatore) [inline monkey/monkey_island/cc/ui/src/components/report-components/security/StolenCredentialsTable.tsx:57]: Can we use `for...in`?

**Comment by shreyamalviya** [comment]
image
image

**Comment by shreyamalviya** [comment]
image
image

**Review by ilija-lazoroski — APPROVED** [review]
