### PR TITLE
UI router bugfix and loading screen

### LINKED ISSUE #739: Doesn't redirect to "Login" page on Map page
## Describe the bug
Doesn't redirect to "Login" page on Map page, once JWT expires

## To Reproduce
1. Wait until JWT expires
2. Go to/refresh http://localhost:5000/infection/map
3. See blank page

## Expected behavior
Should redirect to Login/Register

### PR DESCRIPTION
**Pull request by VakarisZ**
Fixed white screen on map/going to map bug, implemented loading screen while UI is waiting for login status

# What is this? 
Fixes #739 . 
Implemented loading screen while UI is waiting for login status.

## Proof that it works
This is how it looks like, when island is waiting for login status (on page refresh for example):
image

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js [hunk 1]
```diff
@@ -1,10 +1,9 @@
 import React from 'react';
 import {Row, Col, Container, Form, Button} from 'react-bootstrap';
-import Particles from 'react-particles-js';
 
 import AuthService from '../../services/AuthService';
-import {particleParams} from '../../styles/components/particle-component/AuthPageParams';
 import monkeyDetective from '../../images/detective-monkey.svg';
+import ParticleBackground from "../ui-components/ParticleBackground";
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/pages/RegisterPage.js:6]: should change to single quotes

**Review by ShayNehmad — APPROVED** [review]
