### PR TITLE
3873 fix hanging service

### LINKED ISSUE #3873: Appimage service hangs waiting for island input
## Describe the bug

If an input from island cmd is required  AppImage service hangs. 

## To Reproduce
1. Install the island as a service
2. Install another version of island as a service
3. Run service
4. Service hangs waiting for input to delete the data directory

## Expected behavior

Service should probably exit saying "another island service is already installed". Uninstalling the service should remove the data directory.

## Machine version (please complete the following information):
 - OS:  Linux

### PR DESCRIPTION
**Pull request by ilija-lazoroski**
# What does this PR do?

Fixes #3873 .

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [x] Was the documentation framework updated to reflect the changes?
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [x] Added relevant unit tests?
* [x] Do all unit tests pass?
* [x] Do all end-to-end tests pass?
* [x] Any other testing performed?
    > Tested by {Running the Monkey locally with relevant config/running Island/...}
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

File: build_scripts/appimage/install-infection-monkey-service.sh [hunk 1]
```diff
@@ -31,13 +32,20 @@ echo_help() {
...
   copy_appimage
   install_systemd_unit "$1"
 
   echo "The Infection Monkey service has been installed and will start on boot."
   echo "Run 'systemctl start infection-monkey' to start the service now."
 }
 
+exit_if_service_installed() {
+  if sudo systemctl list-units --full --all | grep -Fq "${SYSTEMD_UNIT_FILENAME}"; then
+    die "Error: Service ${SYSTEMD_UNIT_FILENAME} is already installed."
```
Comment (mssalvatore) [inline build_scripts/appimage/install-infection-monkey-service.sh:45]: Perhaps we should add uninstallation instructions? "Please uninstall with `sudo ... service --uninstall` before attempting to install" or something like that?

File: build_scripts/appimage/install-infection-monkey-service.sh [hunk 2]
```diff
@@ -69,6 +77,10 @@ EOF
 }
 
 uninstall_service() {
+  if [ -d "${MONKEY_DATA_DIR}" ] ; then
+    sudo rm -rf "${MONKEY_DATA_DIR}"
```
Comment (mssalvatore) [inline build_scripts/appimage/install-infection-monkey-service.sh:81]: Running `sudo rm -rf` is super dangerous. There could be symlinks in this directory and who knows what could be removed.

We can run sudo with `-u <USER>` to limit the impact.

**Review by mssalvatore — CHANGES_REQUESTED** [review]

**Review by mssalvatore — APPROVED** [review]
