### PR TITLE
Fix eslint errors

### LINKED ISSUE #1836: Fix Travis build
The Travis build is currently failing. Fix it.

## Tasks

- [x] Fix eslint errors (0d) - @shreyamalviya 
- [x] Fix swimm errors (0d) @mssalvatore

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #1836 

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [ ] ~Was the CHANGELOG.md updated to reflect the changes?~
* [ ] ~Was the documentation framework updated to reflect the changes?~

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Travis build passes
* [ ] ~If applicable, add screenshots or log transcripts of the feature working~

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/pages/MapPage.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ class MapPageComponent extends AuthComponent {
         body: JSON.stringify({kill_time: Date.now() / 1000.0})
       })
       .then(res => res.json())
-      .then(res => {this.setState({killPressed: true})});
+      .then(_res => {this.setState({killPressed: true})});
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/pages/MapPage.js:95]: We can do `.then(() => {this.setState({killPressed: true})});`

**Review by VakarisZ — APPROVED** [review]
One optional fix

**Review by ilija-lazoroski — APPROVED** [review]
