### PR TITLE
Fix exploit percentage in security report

### LINKED ISSUE #2954: Security report shows NAN if no machines to exploit
## Describe the bug
The Security report will show **NaN% of scanned machines exploited** if no machines were discovered.

## To Reproduce
1. Don't configure any targets to scan
2. Run the monkey
3. Navigate to the Security report, under **The Network from Infection Monkey's Eyes**, and observe **NaN% of scanned machines exploited**

## Expected behavior
It should show a 0 instead of a NAN

### PR DESCRIPTION
**Pull request by shreyamalviya**
# What does this PR do?

Fixes #2954

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing?
* [x] Was the CHANGELOG.md updated to reflect the changes?
* [ ] ~Was the documentation framework updated to reflect the changes?~
* [x] Have you checked that you haven't introduced any duplicate code?

## Testing Checklist

* [ ] ~Added relevant unit tests?~
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested Island
* [x] If applicable, add screenshots or log transcripts of the feature working

image

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js [hunk 1]
```diff
@@ -241,6 +241,11 @@ class ReportPageComponent extends AuthComponent {
   generateReportGlanceSection() {
     let exploitPercentage =
       (100 * this.state.report.glance.exploited_cnt) / this.state.report.glance.scanned.length;
+
+    if (isNaN(exploitPercentage)) {
+      exploitPercentage = 0;
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js:246]: 0 of 0 is not 0%. Instead of displaying percentages we should simply not show the "percentage" section. I'm not sure what it adds anyway...

**Comment by VakarisZ** [comment]
image
image

**Review by ilija-lazoroski — APPROVED** [review]
Looks good enough to me!
