### PR TITLE
150/resize network map

### LINKED ISSUE #150: Monkey Island Map component doesn't scale to window size
**Describe the bug**
The Infection Map doesn't scale its size to the browser window's size when it's resized.

**To Reproduce**
1. Open browser with small window size.
2. Go to Infection Map page.
3. Maximize window

**Expected behavior**
The Map will resize accordingly.

**Machine version(please complete the following information):**
 - OS: Windows. Probably Linux as well.

### PR DESCRIPTION
**Pull request by mssalvatore**
# What does this PR do? 

Fixes #150 - Scale Monkey Island map to window size

## PR Checklist
* [x] Have you added an explanation of what your changes do and why you'd like to include them?
* [x] Is the TravisCI build passing? 
* [ ] Was the documentation framework updated to reflect the changes? (N/A)

## Testing Checklist

* [ ] Added relevant unit tests? (N/A)
* [x] Have you successfully tested your changes locally? Elaborate:
    > Tested by running the monkey in the monkeyzoo environment
* [x] If applicable, add screenshots or log transcripts of the feature working

map_resize

### CODE REVIEW

File: monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js [hunk 1]
```diff
@@ -12,12 +12,14 @@ class GraphWrapper extends React.Component {
     let newOptions = null;
     if(this.props.options !== undefined){
       newOptions = this.props.options;
-      newOptions.height = this.props.containerHeight.toString() + 'px';
-      newOptions.width = this.props.containerWidth.toString() + 'px';
     }
-    return (<Graph graph={this.props.graph} options={newOptions} events={this.props.events}/>)
+    return (
+      <div class={'net-graph-wrapper'}>
+        <Graph graph={this.props.graph} options={newOptions} events={this.props.events}/>
```
Comment (VakarisZ) [inline monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js:18]: Tried it like this?
```suggestion
        <Graph graph={this.props.graph} options={newOptions} events={this.props.events} className={'net-graph-wrapper'}/>
```

**Review by VakarisZ — APPROVED** [review]
Wow, nice!

File: monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js (hunk 1 above)
Comment (mssalvatore) [reply monkey/monkey_island/cc/ui/src/components/reactive-graph/ReactiveGraph.js:18]: @VakarisZ  Yeah, it doesn't work because the `Graph` component ignores the `className` property. https://github.com/crubier/react-graph-vis/blob/b86b4ebfe2112f3a6ae946ab3806c7d995502f3a/lib/index.js#L256-L260

I could add the style instead of adding a class name, but I'd rather we control as much of the style in `.css` files as possible, rather than having them hard coded in the JSX.
